name: Github Actions demo
on: 
    schedule:
        - cron: '0 0 * * *'
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                    node-version: '18'
                    cache: 'npm'
            - run: npm install
              env:
                DB_HOST: ${{ secrets.DB_HOST }}
                DB_USER: ${{ secrets.DB_USER }}
                DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                DB_NAME: ${{ secrets.DB_NAME }}
                DB_PORT: ${{ secrets.DB_PORT }}
            - name: Scrappear
              run: npm run scrape
