name: Cron-job scrapping
on:
  push:
  schedule:
    - cron: '0 6 * * 1,3,5,6'

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: install dependencies
        run: npm install
      - name: Scrappear
        run: npm run scrape
